  on:
    push:
      branches: [ main ]
    pull_request:
      branches: [ main ]   

  jobs:
    build:
       runs-on: ubuntu-latest
       steps:
        - uses: actions/checkout@v2
        - name: Set up Python 3.8
          uses: actions/setup-python@v2
          with:
            python-version: 3.8
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install flake8 pytest pytest-cov
            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        - name: Set env
          run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
        - name: Echo Version Tag
          run: |
            echo $RELEASE_VERSION
            echo ${{ env.RELEASE_VERSION }}
        - name: Create Download Directory
          run: mkdir downloads
          
        - name: Upload release asset
          uses: actions/upload-release-asset@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            upload_url: ${{ steps.create-new-release.outputs.upload_url }}
            asset_path: ./content.zip
            asset_name: ${{ env.RELEASE_VERSION }}.zip
            asset_content_type: application/zip

          -name: Send mail
          -uses: dawidd6/action-send-mail@v2
           with:
                server_address: smtp.gmail.com
                server_port: 465
                username: ${{secrets.MAIL_USERNAME}}
                password: ${{secrets.MAIL_PASSWORD}}
                subject: Github Actions job result
                # Literal body:
                body: Build job of ${{github.repository}} completed successfully!
                # Read file contents as body:      
                to: nurhannanis@gmail.com #ict.eti.consultants@gmail.com
                from: nurhannanis@gmail.com # <user@example.com>
           

             # Optional carbon copy recipients
             #cc: kyloren@starkiller.com,leia@alderaan.com
              # Optional blind carbon copy recipients
              #bcc: r2d2@jakku.com,hansolo@milleniumfalcon.com
              # Optional content type (defaults to text/plain):
              #content_type: text/html
              # Optional converting Markdown to HTML (set content_type to text/html too):
              #convert_markdown: true
              # Optional attachments:
              #attachments: attachments.zip,git.diff,./dist/static/main.js


