name: Release Notification to Client
  
on:
    push:
      branches: [ main ] 
      
runs-on: ubuntu-latest          
      -name: Send mail
      -uses: dawidd6/action-send-mail@v2
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{secrets.MAIL_USERNAME}}
        password: ${{secrets.MAIL_PASSWORD}}
        subject: Github Actions job result
        # Literal body:
        body: Build release number ${{release_version}} of ETI Team 3 is completed successfully!
        # Read file contents as body:      
        to: ict.eti.consultants@gmail.com
        from: nurhannanis@gmail.com # <user@example.com>
